server:
  port: 8001

spring:
  application:
    name: ms-diners

eureka:
  instance:
    prefer-ip-address: true   # Ip地址端口注册的方式
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/