server:
  port: 80

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   # 开启配置注册中心进行路由功能
          lower-case-service-id: true
      routes:
        - id: ms-diners
          url: lb://ms-diners   # load balance

eureka:
  instance:
    prefer-ip-address: true   # Ip地址端口注册的方式
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/