server:
  port: 8002

spring:
  application:
    name: ms-oauth2-server
  profiles:
    active: dev

client:
  oauth2:
    client-id: appId
    secret: 123456
    # 授权类型
    grant_types:
      - password
      - refresh_token
    # token 有效时间，单位秒
    token-validity-time: 3600
    refresh-token-validity-time: 3600
    # 客户端访问范围
    scopes:
      - api
      - all
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

# 指标监控健康检查
management:
  endpoints:
    web:
      exposure:
        include: "*"  # 暴露的端点
