server:
  port: 8007

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

spring:
  application:
    name: order-service-manager
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  resources:
    add-mappings: false   # true: 如果所有的controller都没有命中，则使用默认的静态资源处理器做匹配，匹配不上和false一样被全局异常捕获
  mvc:
    throw-exception-if-no-handler-found: true    #找不到handler（所有匹配的controller）就抛出对应的异常

mapper:
  mappers: com.baomidou.mybatisplus.core.mapper.BaseMapper
  not-empty: false        # 在进行数据库操作的时候，判断表达式 username != null, 是否追加 username != ''
  identity: MYSQL
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启mybatis日志
  type-aliases-package: com.aiolos.food.pojo
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    org.springframework.cloud.loadbalancer.config.BlockingLoadBalancerClientAutoConfiguration: error

service:
  name:
    ms-oauth-server: http://ms-oauth2-server/
    ms-diners: http://ms-diners/